import { Sort } from '../service/Sort';
import { testData } from './testData';

test('check alphabetical sorting in ascending order', () => {
    const sortObj = new Sort({ type: 'nameAZ' }, testData);
    expect(sortObj.sortByNameAZ()).toEqual([
        {
            id: 6,
            name: 'honor 50',
            price: 800,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/honor50blue.webp',
            company: 'huawei',
            camResolution: '16 Mp',
            year: 2020,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 8,
            name: 'honor 50000',
            price: 800,
            color: 'RED',
            description: 'none',
            imageSrc: './assets/images/honor50blue.webp',
            company: 'huawei',
            camResolution: '16 Mp',
            year: 2020,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 4,
            name: 'honor X8',
            price: 550,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/honor8x.webp',
            company: 'huawei',
            camResolution: '12 Mp',
            year: 2021,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 5,
            name: 'iphone 11',
            price: 550,
            color: 'black',
            description: 'none',
            imageSrc: './assets/images/iphone11black.webp',
            company: 'apple',
            camResolution: '64 Mp',
            year: 2021,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 11,
            name: 'iphone 13 128gb',
            price: 950,
            color: 'grey',
            description: 'none',
            imageSrc: './assets/images/iphone11black.webp',
            company: 'apple',
            camResolution: '64 Mp',
            year: 2021,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 7,
            name: 'iphone11',
            price: 990,
            color: 'white',
            description: 'none',
            imageSrc: './assets/images/iphone11.webp',
            company: 'apple',
            camResolution: '12 Mp',
            year: 2020,
            onStorage: 7,
            inCart: false,
        },
        {
            id: 13,
            name: 'iphone12',
            price: 987,
            color: 'white',
            description: 'none',
            imageSrc: './assets/images/iphone11white.webp',
            company: 'apple',
            camResolution: '20 Mp',
            year: 2018,
            onStorage: 3,
            inCart: false,
        },
        {
            id: 2,
            name: 'realme c25',
            price: 300,
            color: 'grey',
            description: 'none',
            imageSrc: './assets/images/realmegrey.webp',
            company: 'realme',
            camResolution: '8 Mp',
            year: 2012,
            onStorage: 3,
            inCart: false,
        },
        {
            id: 3,
            name: 'realme c5',
            price: 120,
            color: 'yellow',
            description: 'none',
            imageSrc: './assets/images/realmeyellow.webp',
            company: 'realme',
            camResolution: '12 Mp',
            year: 2013,
            onStorage: 4,
            inCart: false,
        },
        {
            id: 1,
            name: 'redmi 9c',
            price: 250,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/redmi9c.webp',
            company: 'xiaomi',
            camResolution: '12 Mp',
            year: 2020,
            onStorage: 2,
            inCart: false,
        },
        {
            id: 12,
            name: 'samsung galaxy a3',
            price: 130,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/galaxya03.webp',
            company: 'samsung',
            camResolution: '13 Mp',
            year: 2020,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 10,
            name: 'zte blade a51',
            price: 680,
            color: 'black',
            description: 'none',
            imageSrc: './assets/images/honor50blue.webp',
            company: 'zte',
            camResolution: '12 Mp',
            year: 2011,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 9,
            name: 'zte blade v8',
            price: 250,
            color: 'green',
            description: 'none',
            imageSrc: './assets/images/somechinephonegreen.webp',
            company: 'zte',
            camResolution: '16 Mp',
            year: 2017,
            onStorage: 15,
            inCart: false,
        },
    ]);
});

test('check alphabetical sorting in descending order', () => {
    const sortObj = new Sort({ type: 'nameZA' }, testData);
    expect(sortObj.sortByNameZA()).toEqual([
        {
            id: 9,
            name: 'zte blade v8',
            price: 250,
            color: 'green',
            description: 'none',
            imageSrc: './assets/images/somechinephonegreen.webp',
            company: 'zte',
            camResolution: '16 Mp',
            year: 2017,
            onStorage: 15,
            inCart: false,
        },
        {
            id: 10,
            name: 'zte blade a51',
            price: 680,
            color: 'black',
            description: 'none',
            imageSrc: './assets/images/honor50blue.webp',
            company: 'zte',
            camResolution: '12 Mp',
            year: 2011,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 12,
            name: 'samsung galaxy a3',
            price: 130,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/galaxya03.webp',
            company: 'samsung',
            camResolution: '13 Mp',
            year: 2020,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 1,
            name: 'redmi 9c',
            price: 250,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/redmi9c.webp',
            company: 'xiaomi',
            camResolution: '12 Mp',
            year: 2020,
            onStorage: 2,
            inCart: false,
        },
        {
            id: 3,
            name: 'realme c5',
            price: 120,
            color: 'yellow',
            description: 'none',
            imageSrc: './assets/images/realmeyellow.webp',
            company: 'realme',
            camResolution: '12 Mp',
            year: 2013,
            onStorage: 4,
            inCart: false,
        },
        {
            id: 2,
            name: 'realme c25',
            price: 300,
            color: 'grey',
            description: 'none',
            imageSrc: './assets/images/realmegrey.webp',
            company: 'realme',
            camResolution: '8 Mp',
            year: 2012,
            onStorage: 3,
            inCart: false,
        },
        {
            id: 13,
            name: 'iphone12',
            price: 987,
            color: 'white',
            description: 'none',
            imageSrc: './assets/images/iphone11white.webp',
            company: 'apple',
            camResolution: '20 Mp',
            year: 2018,
            onStorage: 3,
            inCart: false,
        },
        {
            id: 7,
            name: 'iphone11',
            price: 990,
            color: 'white',
            description: 'none',
            imageSrc: './assets/images/iphone11.webp',
            company: 'apple',
            camResolution: '12 Mp',
            year: 2020,
            onStorage: 7,
            inCart: false,
        },
        {
            id: 11,
            name: 'iphone 13 128gb',
            price: 950,
            color: 'grey',
            description: 'none',
            imageSrc: './assets/images/iphone11black.webp',
            company: 'apple',
            camResolution: '64 Mp',
            year: 2021,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 5,
            name: 'iphone 11',
            price: 550,
            color: 'black',
            description: 'none',
            imageSrc: './assets/images/iphone11black.webp',
            company: 'apple',
            camResolution: '64 Mp',
            year: 2021,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 4,
            name: 'honor X8',
            price: 550,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/honor8x.webp',
            company: 'huawei',
            camResolution: '12 Mp',
            year: 2021,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 8,
            name: 'honor 50000',
            price: 800,
            color: 'RED',
            description: 'none',
            imageSrc: './assets/images/honor50blue.webp',
            company: 'huawei',
            camResolution: '16 Mp',
            year: 2020,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 6,
            name: 'honor 50',
            price: 800,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/honor50blue.webp',
            company: 'huawei',
            camResolution: '16 Mp',
            year: 2020,
            onStorage: 10,
            inCart: false,
        },
    ]);
});

test('check price sorting in ascending order', () => {
    const sortObj = new Sort({ type: 'name19' }, testData);
    expect(sortObj.sortByPrice19()).toEqual([
        {
            id: 3,
            name: 'realme c5',
            price: 120,
            color: 'yellow',
            description: 'none',
            imageSrc: './assets/images/realmeyellow.webp',
            company: 'realme',
            camResolution: '12 Mp',
            year: 2013,
            onStorage: 4,
            inCart: false,
        },
        {
            id: 12,
            name: 'samsung galaxy a3',
            price: 130,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/galaxya03.webp',
            company: 'samsung',
            camResolution: '13 Mp',
            year: 2020,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 1,
            name: 'redmi 9c',
            price: 250,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/redmi9c.webp',
            company: 'xiaomi',
            camResolution: '12 Mp',
            year: 2020,
            onStorage: 2,
            inCart: false,
        },
        {
            id: 9,
            name: 'zte blade v8',
            price: 250,
            color: 'green',
            description: 'none',
            imageSrc: './assets/images/somechinephonegreen.webp',
            company: 'zte',
            camResolution: '16 Mp',
            year: 2017,
            onStorage: 15,
            inCart: false,
        },
        {
            id: 2,
            name: 'realme c25',
            price: 300,
            color: 'grey',
            description: 'none',
            imageSrc: './assets/images/realmegrey.webp',
            company: 'realme',
            camResolution: '8 Mp',
            year: 2012,
            onStorage: 3,
            inCart: false,
        },
        {
            id: 4,
            name: 'honor X8',
            price: 550,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/honor8x.webp',
            company: 'huawei',
            camResolution: '12 Mp',
            year: 2021,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 5,
            name: 'iphone 11',
            price: 550,
            color: 'black',
            description: 'none',
            imageSrc: './assets/images/iphone11black.webp',
            company: 'apple',
            camResolution: '64 Mp',
            year: 2021,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 10,
            name: 'zte blade a51',
            price: 680,
            color: 'black',
            description: 'none',
            imageSrc: './assets/images/honor50blue.webp',
            company: 'zte',
            camResolution: '12 Mp',
            year: 2011,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 6,
            name: 'honor 50',
            price: 800,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/honor50blue.webp',
            company: 'huawei',
            camResolution: '16 Mp',
            year: 2020,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 8,
            name: 'honor 50000',
            price: 800,
            color: 'RED',
            description: 'none',
            imageSrc: './assets/images/honor50blue.webp',
            company: 'huawei',
            camResolution: '16 Mp',
            year: 2020,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 11,
            name: 'iphone 13 128gb',
            price: 950,
            color: 'grey',
            description: 'none',
            imageSrc: './assets/images/iphone11black.webp',
            company: 'apple',
            camResolution: '64 Mp',
            year: 2021,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 13,
            name: 'iphone12',
            price: 987,
            color: 'white',
            description: 'none',
            imageSrc: './assets/images/iphone11white.webp',
            company: 'apple',
            camResolution: '20 Mp',
            year: 2018,
            onStorage: 3,
            inCart: false,
        },
        {
            id: 7,
            name: 'iphone11',
            price: 990,
            color: 'white',
            description: 'none',
            imageSrc: './assets/images/iphone11.webp',
            company: 'apple',
            camResolution: '12 Mp',
            year: 2020,
            onStorage: 7,
            inCart: false,
        },
    ]);
});

test('check price sorting in descending order', () => {
    const sortObj = new Sort({ type: 'name91' }, testData);
    expect(sortObj.sortByPrice91()).toEqual([
        {
            id: 7,
            name: 'iphone11',
            price: 990,
            color: 'white',
            description: 'none',
            imageSrc: './assets/images/iphone11.webp',
            company: 'apple',
            camResolution: '12 Mp',
            year: 2020,
            onStorage: 7,
            inCart: false,
        },
        {
            id: 13,
            name: 'iphone12',
            price: 987,
            color: 'white',
            description: 'none',
            imageSrc: './assets/images/iphone11white.webp',
            company: 'apple',
            camResolution: '20 Mp',
            year: 2018,
            onStorage: 3,
            inCart: false,
        },
        {
            id: 11,
            name: 'iphone 13 128gb',
            price: 950,
            color: 'grey',
            description: 'none',
            imageSrc: './assets/images/iphone11black.webp',
            company: 'apple',
            camResolution: '64 Mp',
            year: 2021,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 8,
            name: 'honor 50000',
            price: 800,
            color: 'RED',
            description: 'none',
            imageSrc: './assets/images/honor50blue.webp',
            company: 'huawei',
            camResolution: '16 Mp',
            year: 2020,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 6,
            name: 'honor 50',
            price: 800,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/honor50blue.webp',
            company: 'huawei',
            camResolution: '16 Mp',
            year: 2020,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 10,
            name: 'zte blade a51',
            price: 680,
            color: 'black',
            description: 'none',
            imageSrc: './assets/images/honor50blue.webp',
            company: 'zte',
            camResolution: '12 Mp',
            year: 2011,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 5,
            name: 'iphone 11',
            price: 550,
            color: 'black',
            description: 'none',
            imageSrc: './assets/images/iphone11black.webp',
            company: 'apple',
            camResolution: '64 Mp',
            year: 2021,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 4,
            name: 'honor X8',
            price: 550,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/honor8x.webp',
            company: 'huawei',
            camResolution: '12 Mp',
            year: 2021,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 2,
            name: 'realme c25',
            price: 300,
            color: 'grey',
            description: 'none',
            imageSrc: './assets/images/realmegrey.webp',
            company: 'realme',
            camResolution: '8 Mp',
            year: 2012,
            onStorage: 3,
            inCart: false,
        },
        {
            id: 9,
            name: 'zte blade v8',
            price: 250,
            color: 'green',
            description: 'none',
            imageSrc: './assets/images/somechinephonegreen.webp',
            company: 'zte',
            camResolution: '16 Mp',
            year: 2017,
            onStorage: 15,
            inCart: false,
        },
        {
            id: 1,
            name: 'redmi 9c',
            price: 250,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/redmi9c.webp',
            company: 'xiaomi',
            camResolution: '12 Mp',
            year: 2020,
            onStorage: 2,
            inCart: false,
        },
        {
            id: 12,
            name: 'samsung galaxy a3',
            price: 130,
            color: 'blue',
            description: 'none',
            imageSrc: './assets/images/galaxya03.webp',
            company: 'samsung',
            camResolution: '13 Mp',
            year: 2020,
            onStorage: 10,
            inCart: false,
        },
        {
            id: 3,
            name: 'realme c5',
            price: 120,
            color: 'yellow',
            description: 'none',
            imageSrc: './assets/images/realmeyellow.webp',
            company: 'realme',
            camResolution: '12 Mp',
            year: 2013,
            onStorage: 4,
            inCart: false,
        },
    ]);
});
