const carModels = [
    'ILX ',
    'Integra ',
    'MDX ',
    'NSX ',
    'RDX ',
    'TLX ',
    'Giulia ',
    'Stelvio ',
    'Tonale ',
    'A3 ',
    'A4 ',
    'A5 ',
    'A6 ',
    'A7 ',
    'A8 ',
    'Allroad ',
    'e-tron ',
    'E-Tron GT ',
    'Q3 ',
    'Q4 E-Tron ',
    'Q5 ',
    'Q5 ',
    'Q7 ',
    'Q8 ',
    'R8 ',
    'S4 ',
    'TT ',
    'Bentayga ',
    'Flying Spur ',
    '2 Series ',
    '2 Series Gran Coupe ',
    '3 Series ',
    '4 Series ',
    '5 Series ',
    '7 Series ',
    '7 Series ',
    '8 Series ',
    'i4 ',
    'i7 ',
    'iX ',
    'X1 ',
    'X1 ',
    'X2 ',
    'X3 ',
    'X4 ',
    'X5 ',
    'X6 ',
    'X7 ',
    'Z4 ',
    'Enclave ',
    'Encore ',
    'Encore GX ',
    'Envision ',
    'CT4 ',
    'CT5 ',
    'Escalade ',
    'Lyriq ',
    'XT4 ',
    'XT5 ',
    'XT5 ',
    'XT6 ',
    'Blazer ',
    'Blazer EV ',
    'Bolt ',
    'Bolt EUV ',
    'Camaro ',
    'Colorado ',
    'Colorado ',
    'Corvette ',
    'Equinox ',
    'Express ',
    'Malibu ',
    'Silverado 1500 ',
    'Silverado 2500HD ',
    'Silverado 3500HD ',
    'Silverado EV ',
    'Spark ',
    'Suburban ',
    'Tahoe ',
    'TrailBlazer ',
    'Traverse ',
    'Trax ',
    '300 ',
    'Pacifica ',
    'Voyager ',
    'Challenger ',
    'Charger ',
    'Durango ',
    '500X ',
    'Ocean ',
    'Bronco ',
    'Bronco Sport ',
    'EcoSport ',
    'Edge ',
    'Escape ',
    'Expedition ',
    'Explorer ',
    'F-150 ',
    'F-150 Lightning ',
    'F-250 ',
    'F-350 ',
    'Maverick ',
    'Mustang ',
    'Mustang Mach-E ',
    'Ranger ',
    'Transit ',
    'Transit Connect ',
    'Electrified G80 ',
    'G70 ',
    'G80 ',
    'G90 ',
    'G90 ',
    'GV60 ',
    'GV70 ',
    'GV80 ',
    'Acadia ',
    'Canyon ',
    'Hummer EV ',
    'Savana ',
    'Sierra 1500 ',
    'Sierra 2500HD ',
    'Sierra 3500HD ',
    'Terrain ',
    'Yukon ',
    'Yukon XL ',
    'Accord ',
    'Civic ',
    'CR-V ',
    'CR-V ',
    'HR-V ',
    'HR-V ',
    'Insight ',
    'Odyssey ',
    'Odyssey ',
    'Passport ',
    'Pilot ',
    'Ridgeline ',
    'Accent ',
    'Elantra ',
    'Ioniq ',
    'Ioniq 5 ',
    'Ioniq 6 ',
    'Kona ',
    'Kona Electric ',
    'Nexo ',
    'Palisade ',
    'Santa Cruz ',
    'Santa Fe ',
    'Sonata ',
    'Tucson ',
    'Veloster ',
    'Venue ',
    'Q50 ',
    'Q60 ',
    'QX50 ',
    'QX55 ',
    'QX60 ',
    'QX80 ',
    'E-Pace ',
    'F-Pace ',
    'F-Type ',
    'I-Pace ',
    'XF ',
    'Cherokee ',
    'Compass ',
    'Gladiator ',
    'Grand Cherokee ',
    'Grand Cherokee L ',
    'Grand Wagoneer ',
    'Renegade ',
    'Wagoneer ',
    'Wrangler ',
    'Carnival ',
    'EV6 ',
    'Forte ',
    'K5 ',
    'Niro ',
    'Niro ',
    'Niro Electric ',
    'Niro Electric ',
    'Rio ',
    'Seltos ',
    'Sorento ',
    'Soul ',
    'Soul ',
    'Sportage ',
    'Sportage ',
    'Stinger ',
    'Telluride ',
    'Defender ',
    'Discovery ',
    'Discovery Sport ',
    'Evoque ',
    'Sport ',
    'Sport ',
    'Velar ',
    'ES ',
    'GX ',
    'IS ',
    'LC ',
    'LS ',
    'LX ',
    'NX ',
    'RC ',
    'RX ',
    'RX ',
    'RX L ',
    'RZ ',
    'UX ',
    'Aviator ',
    'Corsair ',
    'Nautilus ',
    'Navigator ',
    'Air ',
    'Ghibli ',
    'Grecale ',
    'Levante ',
    'Quattroporte ',
    '3 ',
    'CX-30 ',
    'CX-5 ',
    'CX-50 ',
    'CX-9 ',
    'MX-30 ',
    'MX-5 Miata ',
    'A-Class ',
    'AMG GT ',
    'C-Class ',
    'CLA ',
    'CLS ',
    'E-Class ',
    'EQB ',
    'EQE ',
    'EQS ',
    'EQS SUV ',
    'G-Class ',
    'GLA ',
    'GLB ',
    'GLC ',
    'GLC ',
    'GLC Coupe ',
    'GLE ',
    'GLE Coupe ',
    'GLS ',
    'Metris ',
    'S-Class ',
    'Sprinter ',
    'Cooper ',
    'Cooper Clubman ',
    'Cooper Countryman ',
    'Eclipse Cross ',
    'Mirage ',
    'Outlander ',
    'Outlander Sport ',
    'Altima ',
    'Ariya ',
    'Armada ',
    'Frontier ',
    'Kicks ',
    'Leaf ',
    'Maxima ',
    'Murano ',
    'Pathfinder ',
    'Rogue ',
    'Rogue Sport ',
    'Sentra ',
    'Titan ',
    'Titan XD ',
    'Versa ',
    'Z ',
    '2 ',
    '718 Boxster ',
    '718 Cayman ',
    '911 ',
    'Cayenne ',
    'Macan ',
    'Panamera ',
    'Taycan ',
    '1500 ',
    '1500 Classic ',
    '2500 ',
    '3500 ',
    'R1S ',
    'R1T ',
    'Ascent ',
    'BRZ ',
    'Crosstrek ',
    'Forester ',
    'Impreza ',
    'Legacy ',
    'Outback ',
    'Solterra ',
    'WRX ',
    'Cybertruck ',
    'Model 3 ',
    'Model S ',
    'Model X ',
    'Model Y ',
    '4Runner ',
    '86 ',
    'Avalon ',
    'bZ4X ',
    'C-HR ',
    'Camry ',
    'Corolla ',
    'Corolla Cross ',
    'Corolla Hatchback ',
    'Crown ',
    'GR Corolla ',
    'Highlander ',
    'Mirai ',
    'Prius ',
    'Prius Prime ',
    'RAV4 ',
    'RAV4 Prime ',
    'Sequoia ',
    'Sequoia ',
    'Sienna ',
    'Supra ',
    'Tacoma ',
    'Tundra ',
    'Venza ',
    'Arteon ',
    'Atlas ',
    'Atlas Cross Sport ',
    'Golf R ',
    'GTI ',
    'ID4 ',
    'Jetta ',
    'Passat ',
    'Taos ',
    'Tiguan ',
    'C40 ',
    'S60 ',
    'S90 ',
    'V60 ',
];
const carBrands = [
    'Brand ',
    'Acura',
    'Alfa Romeo',
    'Audi',
    'BMW',
    'Bentley',
    'Buick',
    'Cadillac',
    'Chevrolet',
    'Chrysler',
    'Dodge',
    'Fiat',
    'Ford',
    'GMC',
    'Genesis',
    'Honda',
    'Hyundai',
    'Infiniti',
    'Jaguar',
    'Jeep',
    'Kia',
    'Land Rover',
    'Lexus',
    'Lincoln',
    'Lotus',
    'Maserati',
    'Mazda',
    'Mercedes-Benz',
    'Mercury',
    'Mini',
    'Mitsubishi',
    'Nissan',
    'Polestar',
    'Pontiac',
    'Porsche',
    'Ram',
    'Rivian',
    'Rolls-Royce',
    'Saab',
    'Saturn',
    'Scion',
    'Smart',
    'Subaru',
    'Suzuki',
    'Tesla',
    'Toyota',
    'Volkswagen',
    'Volvo',
    'Parent Company ',
    'BMW ',
    'Daimler AG',
    'Ford',
    'General s ',
    'Honda',
    'Hyundai',
    'Mazda',
    'Renault',
    'Stellantis ',
    'Subaru ',
    'Tata',
    'Tesla ',
    'Toyota',
    'Volkswagen',
];

export const generateRandomCar = (): string => {
    const brandIndex = randomInt(0, carBrands.length - 1);
    const modelIndex = randomInt(0, carModels.length - 1);
    return carBrands[brandIndex] + ' ' + carModels[modelIndex];
};

export function randomInt(min: number, max: number): number {
    // получить случайное число от (min-0.5) до (max+0.5)
    const rand = min - 0.5 + Math.random() * (max - min + 1);
    return Math.round(rand);
}

export function generateRandomColor() {
    const letters = '0123456789ABCDEF';
    let color = '#';
    for (let i = 0; i < 6; i++) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}
